config_version: 1
remove_chest_time: 120
unlock_chest_after: -1
allow_break_chests: false
drop_items_after_expire: false
lava_protection: true
void_spawning_chest: false
auto_equip_armor: true
deathchest_fireworks:
  enabled: true
  interval: 5
clickable_message: true
spawn_chest_on_highest_block: false
disabled_worlds:
  - example_world
disabled_regions:
  - example_region
sounds:
  click: UI_BUTTON_CLICK
  gui_open: ENTITY_EXPERIENCE_ORB_PICKUP
hologram:
  death_date_format: "dd.MM.yyyy hh:mm"
  lines:
  - "%locked%"
  - "Died %death_date%"
  - "Owner: %player%"
  - "%timeleft% left"
deathchest_inv_title: "&7%player%'s DeathChest"