#Config version, DO NOT CHANGE!
config_version: 1
#Enable debug messages in console?
debug_messages: false
#Expire groups and permissions for each group. Please sort groups from highest permission to lowest. Last group should be default.
expire_groups:
  default:
    permission: deathchestpro.expire.default
    teleport_cost: 0
    unlock_after: -1
    time: 60
#Can chest be broken?
allow_break_chests: false
#Can killer loot player's chest?
allow_killer_looting: false
#Should items drop when chest expires?
drop_items_after_expire: false
#Should chest be spawned if player died in lava?
lava_spawning: true
#Should chest be spawned above lava if player has died in lava ?
lava_protection: true
#Should glass cage be spawned around chest if played died in lava?
old_lava_protection: false
#Should chest be spawned if player died in void (or void damage)?
void_spawning_chest: true
#Should it auto equip armor to player during fastlooting?
auto_equip_armor: true
#Should players click on message to teleport to their chest?
clickable_message: true
#Should the chest be spawned on highest possible block, or where player died?
spawn_chest_on_highest_block: false
#Should the chest be spawned when player killed player ?
spawn_chest_on_pvp_kill: true
#Should the chest countdown start right after player died or after he respawns?
start_timer_at_death: false
#Should also player experience be stored? They will be restored once player loots his chest.
store_experience: false
#Percentage amount of player's experience stored. Modify only if 'store_experience' is true.
store_experience_percent: 100.0
#How many chests can players have maximally at one time ?
max_player_chests: 3
#Teleport cooldown
teleport_cooldown: 10
#Deatchest firework settings
deathchest_fireworks:
  #Should fireworks spawn?
  enabled: true
  #Interval between each firework
  interval: 5
#Worlds where deathchest will not spawn
disabled_worlds:
  - example_world
#Regions where deathchest will not spawn
disabled_regions:
  - example_region
#GUI Sounds
sounds:
  click: UI_BUTTON_CLICK
  gui_open: ENTITY_EXPERIENCE_ORB_PICKUP
#Hologram settings
hologram:
  #Should hologram be enabled?
  enabled: true
  #Date format. Visit https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for more help
  death_date_format: "dd.MM.yyyy hh:mm"
  #Lines displayed on hologram. Accepts placeholders %locked%, %death_date%, %player%, %timeleft%
  lines:
    - "%locked%"
    - "%item_count% Items / %xp% XP"
    - "Died %death_date%"
    - "Owner: %player%"
    - "%timeleft% left"
#Name of chest's inventory
deathchest_inv_title: "&7%player%'s DeathChest"
placeholders_format:
  location: "%x%, %y%, %z%, %world%"
