remove_chest_time: 120
allow_break_chests: false
drop_items_after_expire: false
deathchest_fireworks: true
spawn_chest_on_highest_block: false
disabled_worlds:
 - example_world
sounds:
  click: UI_BUTTON_CLICK
  gui_open: ENTITY_EXPERIENCE_ORB_PICKUP
hologram:
  display_player_head: true
  lines:
  - "%locked%"
  - "Owner: %player%"
  - "%timeleft% left"