main: sk.drawethree.deathchestpro.DeathChestPro
version: ${project.version}
api-version: 1.13
name: DeathChestPro
author: TheRealDrawe
softdepend: [Residence, PlaceholderAPI, Multiverse-Core, DeathFeathers, WorldGuard, GriefPrevention, WorldEdit, FastAsyncWorldEdit, Vault]
permissions:
  deathchestpro.*:
    description: All DeathChestPro permissions
    default: op
    children:
      deathchestpro.chest: true
      deathchestpro.lock: true
      deathchestpro.see: true
      deathchestpro.reload: true
      deathchestpro.teleport: true
      deathchestpro.expire.default: true
  deathchestpro.player:
    description: Default player permissions
    default: true
    children:
      deathchestpro.chest: false
      deathchestpro.lock: false
      deathchestpro.list: false
      deathchestpro.fastloot: false
      deathchestpro.expire.default: true
  deathchestpro.chest:
    description: Allows to spawn a chest after player's death
    default: op
  deathchestpro.lock:
    description: Allows to automatically lock a deathchest after death
    default: op
  deathchestpro.lock.bypass:
    description: Allows to bypass a lock
    default: op
  deathchestpro.see:
    description: Allows player to see content of deathchests from list
    default: op
  deathchestpro.see.others:
    description: Allows to see others chest contents
    default: op
  deathchestpro.reload:
    description: Allows to reload plugin
    default: op
  deathchestpro.list:
    description: Allows to open up your deathchest list
    default: op
  deathchestpro.teleport:
    description: Allows to teleport to your deathchest
    default: op
  deathchestpro.fastloot:
    description: Allows to fast loot your chest
    default: op
  deathchestpro.expire.default:
    description: Default expire time
    default: true
commands:
  deathchest:
    aliases: [dc,dcp]
    description: DeathChestPro Command