main: sk.drawethree.deathchestpro.DeathChestPro
version: 1.1
api-version: 1.13
name: DeathChestPro
author: TheRealDrawe
softdepend: [HolographicDisplays]
permissions:
  deathchestpro.*:
    description: All DeathChestPro permissions
    children:
      deathchestpro.chest: true
      deathchestpro.lock: true
      deathchestpro.see: true
      deathchestpro.reload: true
  deathchestpro.chest:
    description: Allows to spawn a chest after player's death
    default: op
  deathchestpro.lock:
    description: Allows to automatically lock a deathchest after death
    default: op
  deathchestpro.lock.bypass:
    description: Allows to bypass a lock
    default: op
  deathchestpro.see:
    description: Allows player to see content of deathchests
    default: op
  deathchestpro.reload:
    description: Allows to reload plugin
    default: op
commands:
  deathchest:
   aliases: [dc,dcp]
   usage: /<command>
   description: DeathChestPro Command