main: sk.drawethree.deathchestpro.DeathChestPro
version: 1.2.1
api-version: 1.13
name: DeathChestPro
author: TheRealDrawe
softdepend: [HolographicDisplays, Residence, DeathFeathers]
permissions:
  deathchestpro.*:
    description: All DeathChestPro permissions
    default: op
    children:
      deathchestpro.chest: true
      deathchestpro.lock: true
      deathchestpro.see: true
      deathchestpro.reload: true
      deathchestpro.teleport: true
  deathchestpro.chest:
    description: Allows to spawn a chest after player's death
    default: op
  deathchestpro.lock:
    description: Allows to automatically lock a deathchest after death
    default: op
  deathchestpro.lock.bypass:
    description: Allows to bypass a lock
    default: op
  deathchestpro.see:
    description: Allows player to see content of deathchests
    default: op
  deathchestpro.reload:
    description: Allows to reload plugin
    default: op
  deathchestpro.list:
    description: Allows to open up your deathchest list
    default: true
  deathchestpro.teleport:
    description: Allows to teleport to your deathchest
    default: op
commands:
  deathchest:
   aliases: [dc,dcp]
   description: DeathChestPro Command